//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Avtomatizaciya_zakupok2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Отчет о закупках.
    /// </summary>
    // *** Start programmer edit section *** (ОтчетОЗакупках CustomAttributes)

    // *** End programmer edit section *** (ОтчетОЗакупках CustomAttributes)
    [AutoAltered()]
    [Caption("Отчет о закупках")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОтчетОЗакупкахE", new string[] {
            "Номер",
            "ДатаНачала",
            "ДатаОкончания",
            "Организация",
            "Склад",
            "Контрагент",
            "СостОтгрузки",
            "СостояниеОплаты",
            "СуммаВклНДС",
            "СуммаДокумента"})]
    [View("ОтчетОЗакупкахL", new string[] {
            "Номер",
            "ДатаНачала",
            "ДатаОкончания",
            "Организация",
            "Склад",
            "Контрагент",
            "СостОтгрузки",
            "СостояниеОплаты",
            "СуммаВклНДС",
            "СуммаДокумента"})]
    public class ОтчетОЗакупках : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.Avtomatizaciya_zakupok2.СостОплаты fСостояниеОплаты;
        
        private IIS.Avtomatizaciya_zakupok2.СостПоставок fСостОтгрузки;
        
        private bool fСуммаВклНДС;
        
        private int fСуммаДокумента;
        
        private System.DateTime fДатаНачала = System.DateTime.Now;
        
        private System.DateTime fДатаОкончания;
        
        private int fНомер;
        
        private string fКонтрагент;
        
        private string fОрганизация;
        
        private string fСклад;
        
        // *** Start programmer edit section *** (ОтчетОЗакупках CustomMembers)

        // *** End programmer edit section *** (ОтчетОЗакупках CustomMembers)

        
        /// <summary>
        /// ДатаНачала.
        /// </summary>
        // *** Start programmer edit section *** (ОтчетОЗакупках.ДатаНачала CustomAttributes)

        // *** End programmer edit section *** (ОтчетОЗакупках.ДатаНачала CustomAttributes)
        public virtual System.DateTime ДатаНачала
        {
            get
            {
                // *** Start programmer edit section *** (ОтчетОЗакупках.ДатаНачала Get start)

                // *** End programmer edit section *** (ОтчетОЗакупках.ДатаНачала Get start)
                System.DateTime result = this.fДатаНачала;
                // *** Start programmer edit section *** (ОтчетОЗакупках.ДатаНачала Get end)

                // *** End programmer edit section *** (ОтчетОЗакупках.ДатаНачала Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтчетОЗакупках.ДатаНачала Set start)

                // *** End programmer edit section *** (ОтчетОЗакупках.ДатаНачала Set start)
                this.fДатаНачала = value;
                // *** Start programmer edit section *** (ОтчетОЗакупках.ДатаНачала Set end)

                // *** End programmer edit section *** (ОтчетОЗакупках.ДатаНачала Set end)
            }
        }
        
        /// <summary>
        /// ДатаОкончания.
        /// </summary>
        // *** Start programmer edit section *** (ОтчетОЗакупках.ДатаОкончания CustomAttributes)

        // *** End programmer edit section *** (ОтчетОЗакупках.ДатаОкончания CustomAttributes)
        public virtual System.DateTime ДатаОкончания
        {
            get
            {
                // *** Start programmer edit section *** (ОтчетОЗакупках.ДатаОкончания Get start)

                // *** End programmer edit section *** (ОтчетОЗакупках.ДатаОкончания Get start)
                System.DateTime result = this.fДатаОкончания;
                // *** Start programmer edit section *** (ОтчетОЗакупках.ДатаОкончания Get end)

                // *** End programmer edit section *** (ОтчетОЗакупках.ДатаОкончания Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтчетОЗакупках.ДатаОкончания Set start)

                // *** End programmer edit section *** (ОтчетОЗакупках.ДатаОкончания Set start)
                this.fДатаОкончания = value;
                // *** Start programmer edit section *** (ОтчетОЗакупках.ДатаОкончания Set end)

                // *** End programmer edit section *** (ОтчетОЗакупках.ДатаОкончания Set end)
            }
        }
        
        /// <summary>
        /// Контрагент.
        /// </summary>
        // *** Start programmer edit section *** (ОтчетОЗакупках.Контрагент CustomAttributes)

        // *** End programmer edit section *** (ОтчетОЗакупках.Контрагент CustomAttributes)
        [StrLen(255)]
        public virtual string Контрагент
        {
            get
            {
                // *** Start programmer edit section *** (ОтчетОЗакупках.Контрагент Get start)

                // *** End programmer edit section *** (ОтчетОЗакупках.Контрагент Get start)
                string result = this.fКонтрагент;
                // *** Start programmer edit section *** (ОтчетОЗакупках.Контрагент Get end)

                // *** End programmer edit section *** (ОтчетОЗакупках.Контрагент Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтчетОЗакупках.Контрагент Set start)

                // *** End programmer edit section *** (ОтчетОЗакупках.Контрагент Set start)
                this.fКонтрагент = value;
                // *** Start programmer edit section *** (ОтчетОЗакупках.Контрагент Set end)

                // *** End programmer edit section *** (ОтчетОЗакупках.Контрагент Set end)
            }
        }
        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (ОтчетОЗакупках.Номер CustomAttributes)

        // *** End programmer edit section *** (ОтчетОЗакупках.Номер CustomAttributes)
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (ОтчетОЗакупках.Номер Get start)

                // *** End programmer edit section *** (ОтчетОЗакупках.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (ОтчетОЗакупках.Номер Get end)

                // *** End programmer edit section *** (ОтчетОЗакупках.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтчетОЗакупках.Номер Set start)

                // *** End programmer edit section *** (ОтчетОЗакупках.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (ОтчетОЗакупках.Номер Set end)

                // *** End programmer edit section *** (ОтчетОЗакупках.Номер Set end)
            }
        }
        
        /// <summary>
        /// Организация.
        /// </summary>
        // *** Start programmer edit section *** (ОтчетОЗакупках.Организация CustomAttributes)

        // *** End programmer edit section *** (ОтчетОЗакупках.Организация CustomAttributes)
        [StrLen(255)]
        public virtual string Организация
        {
            get
            {
                // *** Start programmer edit section *** (ОтчетОЗакупках.Организация Get start)

                // *** End programmer edit section *** (ОтчетОЗакупках.Организация Get start)
                string result = this.fОрганизация;
                // *** Start programmer edit section *** (ОтчетОЗакупках.Организация Get end)

                // *** End programmer edit section *** (ОтчетОЗакупках.Организация Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтчетОЗакупках.Организация Set start)

                // *** End programmer edit section *** (ОтчетОЗакупках.Организация Set start)
                this.fОрганизация = value;
                // *** Start programmer edit section *** (ОтчетОЗакупках.Организация Set end)

                // *** End programmer edit section *** (ОтчетОЗакупках.Организация Set end)
            }
        }
        
        /// <summary>
        /// Склад.
        /// </summary>
        // *** Start programmer edit section *** (ОтчетОЗакупках.Склад CustomAttributes)

        // *** End programmer edit section *** (ОтчетОЗакупках.Склад CustomAttributes)
        [StrLen(255)]
        public virtual string Склад
        {
            get
            {
                // *** Start programmer edit section *** (ОтчетОЗакупках.Склад Get start)

                // *** End programmer edit section *** (ОтчетОЗакупках.Склад Get start)
                string result = this.fСклад;
                // *** Start programmer edit section *** (ОтчетОЗакупках.Склад Get end)

                // *** End programmer edit section *** (ОтчетОЗакупках.Склад Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтчетОЗакупках.Склад Set start)

                // *** End programmer edit section *** (ОтчетОЗакупках.Склад Set start)
                this.fСклад = value;
                // *** Start programmer edit section *** (ОтчетОЗакупках.Склад Set end)

                // *** End programmer edit section *** (ОтчетОЗакупках.Склад Set end)
            }
        }
        
        /// <summary>
        /// СостОтгрузки.
        /// </summary>
        // *** Start programmer edit section *** (ОтчетОЗакупках.СостОтгрузки CustomAttributes)

        // *** End programmer edit section *** (ОтчетОЗакупках.СостОтгрузки CustomAttributes)
        public virtual IIS.Avtomatizaciya_zakupok2.СостПоставок СостОтгрузки
        {
            get
            {
                // *** Start programmer edit section *** (ОтчетОЗакупках.СостОтгрузки Get start)

                // *** End programmer edit section *** (ОтчетОЗакупках.СостОтгрузки Get start)
                IIS.Avtomatizaciya_zakupok2.СостПоставок result = this.fСостОтгрузки;
                // *** Start programmer edit section *** (ОтчетОЗакупках.СостОтгрузки Get end)

                // *** End programmer edit section *** (ОтчетОЗакупках.СостОтгрузки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтчетОЗакупках.СостОтгрузки Set start)

                // *** End programmer edit section *** (ОтчетОЗакупках.СостОтгрузки Set start)
                this.fСостОтгрузки = value;
                // *** Start programmer edit section *** (ОтчетОЗакупках.СостОтгрузки Set end)

                // *** End programmer edit section *** (ОтчетОЗакупках.СостОтгрузки Set end)
            }
        }
        
        /// <summary>
        /// СостояниеОплаты.
        /// </summary>
        // *** Start programmer edit section *** (ОтчетОЗакупках.СостояниеОплаты CustomAttributes)

        // *** End programmer edit section *** (ОтчетОЗакупках.СостояниеОплаты CustomAttributes)
        public virtual IIS.Avtomatizaciya_zakupok2.СостОплаты СостояниеОплаты
        {
            get
            {
                // *** Start programmer edit section *** (ОтчетОЗакупках.СостояниеОплаты Get start)

                // *** End programmer edit section *** (ОтчетОЗакупках.СостояниеОплаты Get start)
                IIS.Avtomatizaciya_zakupok2.СостОплаты result = this.fСостояниеОплаты;
                // *** Start programmer edit section *** (ОтчетОЗакупках.СостояниеОплаты Get end)

                // *** End programmer edit section *** (ОтчетОЗакупках.СостояниеОплаты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтчетОЗакупках.СостояниеОплаты Set start)

                // *** End programmer edit section *** (ОтчетОЗакупках.СостояниеОплаты Set start)
                this.fСостояниеОплаты = value;
                // *** Start programmer edit section *** (ОтчетОЗакупках.СостояниеОплаты Set end)

                // *** End programmer edit section *** (ОтчетОЗакупках.СостояниеОплаты Set end)
            }
        }
        
        /// <summary>
        /// СуммаВклНДС.
        /// </summary>
        // *** Start programmer edit section *** (ОтчетОЗакупках.СуммаВклНДС CustomAttributes)

        // *** End programmer edit section *** (ОтчетОЗакупках.СуммаВклНДС CustomAttributes)
        public virtual bool СуммаВклНДС
        {
            get
            {
                // *** Start programmer edit section *** (ОтчетОЗакупках.СуммаВклНДС Get start)

                // *** End programmer edit section *** (ОтчетОЗакупках.СуммаВклНДС Get start)
                bool result = this.fСуммаВклНДС;
                // *** Start programmer edit section *** (ОтчетОЗакупках.СуммаВклНДС Get end)

                // *** End programmer edit section *** (ОтчетОЗакупках.СуммаВклНДС Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтчетОЗакупках.СуммаВклНДС Set start)

                // *** End programmer edit section *** (ОтчетОЗакупках.СуммаВклНДС Set start)
                this.fСуммаВклНДС = value;
                // *** Start programmer edit section *** (ОтчетОЗакупках.СуммаВклНДС Set end)

                // *** End programmer edit section *** (ОтчетОЗакупках.СуммаВклНДС Set end)
            }
        }
        
        /// <summary>
        /// СуммаДокумента.
        /// </summary>
        // *** Start programmer edit section *** (ОтчетОЗакупках.СуммаДокумента CustomAttributes)

        // *** End programmer edit section *** (ОтчетОЗакупках.СуммаДокумента CustomAttributes)
        public virtual int СуммаДокумента
        {
            get
            {
                // *** Start programmer edit section *** (ОтчетОЗакупках.СуммаДокумента Get start)

                // *** End programmer edit section *** (ОтчетОЗакупках.СуммаДокумента Get start)
                int result = this.fСуммаДокумента;
                // *** Start programmer edit section *** (ОтчетОЗакупках.СуммаДокумента Get end)

                // *** End programmer edit section *** (ОтчетОЗакупках.СуммаДокумента Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтчетОЗакупках.СуммаДокумента Set start)

                // *** End programmer edit section *** (ОтчетОЗакупках.СуммаДокумента Set start)
                this.fСуммаДокумента = value;
                // *** Start programmer edit section *** (ОтчетОЗакупках.СуммаДокумента Set end)

                // *** End programmer edit section *** (ОтчетОЗакупках.СуммаДокумента Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОтчетОЗакупкахE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОтчетОЗакупкахE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОтчетОЗакупкахE", typeof(IIS.Avtomatizaciya_zakupok2.ОтчетОЗакупках));
                }
            }
            
            /// <summary>
            /// "ОтчетОЗакупкахL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОтчетОЗакупкахL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОтчетОЗакупкахL", typeof(IIS.Avtomatizaciya_zakupok2.ОтчетОЗакупках));
                }
            }
        }
    }
}
