import IISAvtomatizaciya_zakupok2КонтрагентыEController from '../i-i-s-avtomatizaciya-zakupok2-контрагенты-e';

var IISAvtomatizaciya_zakupok2КонтрагентыENewController = IISAvtomatizaciya_zakupok2КонтрагентыEController;
export default IISAvtomatizaciya_zakupok2КонтрагентыENewController;
