import IISAvtomatizaciya_zakupok2ПланЗакупокEController from '../i-i-s-avtomatizaciya-zakupok2-план-закупок-e';

var IISAvtomatizaciya_zakupok2ПланЗакупокENewController = IISAvtomatizaciya_zakupok2ПланЗакупокEController;
export default IISAvtomatizaciya_zakupok2ПланЗакупокENewController;
